---
layout: post
title:  docker使用时出现的错误
date:   2018/05/25 13:44
categories:    应用工具
tags: 报错分析 linux docker 
excerpt: Error response from daemon: conflict: unable to delete 0b1edfbffd27 (must be forced) - image is refe  在删除docker本地镜像的时候出现这个错误： Error response from daemon: conflict: unable to delete 0b1edfbffd27 (must 
comment: true
---
* content
{:top}

<h4>Error response from daemon: conflict: unable to delete 0b1edfbffd27 (must be forced) - image is refe</h4>

在删除docker本地镜像的时候出现这个错误： Error response from daemon: conflict: unable to delete 0b1edfbffd27 (must be forced) - image is refe

<pre data-language=><code class="language-shell ">sts@Yudi:~/docker$ sudo docker ps -as

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES                  SIZE
78479ffeba5c        ubuntu              "/bin/bash"         42 hours ago        Exited (0) 42 hours ago                       sharp_wescoff          81 B (virtual 187.7 MB)
0bd2b54678c7        training/webapp     "python app.py"     5 days ago          Exited (0) 5 days ago                         backstabbing_ritchie   0 B (virtual 323.7 MB)
0adbc74a3803        training/webapp     "python app.py"     5 days ago          Exited (143) 5 days ago                       drunk_feynman          0 B (virtual 323.7 MB)
</code></pre>

在删除training/webapp

<pre data-language=><code class="language-shell ">sts@Yudi:~/docker$ sudo docker rm training/webapp
Error response from daemon: conflict: unable to remove repository reference "training/webapp" (must force) - container 0bd2b54678c7 is using its referenced image 54bb4e8718e8
Error: failed to remove images: [training/webapp]
</code></pre>

解决方法：

<pre data-language=><code class="language-shell ">$ sudo docker rm backstabbing_ritchie
</code></pre>

发现在docker进行过bash交互使用命令<code>sudo docker ps -as</code>会显示容器，不使用就不会出现只能使用<code>sudo docker image ls</code>显示
    